version: '2'
services:
    web: 
        image: nginx 
        volumes: 
            - /data/server/conf/nginx:/etc/nginx/conf.d
            - /data/server/conf/certs:/etc/nginx/ssl
        links: 
            - blog 
        ports: 
            - 443:443 
            - 80:80 
                
    blog: 
        image: ghost 
        volumes: 
            - /data/server/data/blog:/var/lib/ghost
        links:
            - db
          
        depends_on: 
            - db 
        ports: 
            - 2368:2368
    
    db: 
        image: mysql
        volumes: 
            - /data/server/data/mysql:/var/lib/mysql
        # ports: 
        #     - 3306:3306 
        environment: 
            - MYSQL_ROOT_PASSWORD=$mysql_pass
   
    # torrent: 
    #     image: lerenn/transmission-seedbox
    #     volumes: 
    #         - /data/server/downloads:/data
    #     ports: 
    #         - 9091:9091 


#Ooj1Ahy5

# 192.99.12.197