version: '2'
services:
    web: 
        image: nginx 
        volumes: 
            - /data/server/conf/nginx:/etc/nginx/conf.d
            - /data/server/conf/certs:/etc/nginx/ssl
        links: 
            - blog
            - gitlab 
        ports: 
            - 443:443 
            - 80:80 
                
    blog: 
        image: ghost 
        volumes: 
            - /data/server/data/blog:/var/lib/ghost
        links:
            - db
          
        depends_on: 
            - db 
        ports: 
            - 2368:2368
    
    db: 
        image: mysql
        volumes: 
            - /data/server/data/mysql:/var/lib/mysql
       
        environment: 
            - MYSQL_ROOT_PASSWORD=$mysql_pass
    gitlab: 
        image: gitlab/gitlab-ce:latest 
        volumes: 
            - /data/server/gitlab/config:/etc/gitlab
            - /data/server/gitlab/logs:/var/log/gitlab
            - /data/server/gitlab/data:/var/opt/gitlab
        # ports: 
        #     - 8080:80 
        environment: 
            - hostname www.kimambo.de/git 
            

            
    # torrent: 
    #     image: lerenn/transmission-seedbox
    #     volumes: 
    #         - /data/server/downloads:/data
    #     ports: 
    #         - 9091:9091 
