version: '3'
services:
    web: 
        image: nginx 
        volumes: 
            - /data/server/conf/nginx:/etc/nginx/conf.d
            - /data/server/conf/certs:/etc/nginx/ssl
        
        ports: 
            - 443:443 
            - 80:80 
                
    blog: 
        image: ghost 
        volumes: 
            - /data/server/data/blog:/var/lib/ghost/content
          
        depends_on: 
            - db 
        ports: 
            - 2368:2368
    
    db: 
        image: mysql
        volumes: 
            - /data/server/data/mysql:/var/lib/mysql
       
        environment: 
            - MYSQL_ROOT_PASSWORD=$mysql_pass
    
