version: '3'
services:
    web: 
        image: nginx 
        volumes: 
            - /data/server/conf/nginx:/etc/nginx/conf.d
            - /data/server/conf/certs:/etc/nginx/ssl
            - /data/server/well-known/:/usr/share/nginx/html
        links: 
            - blog 
        ports: 
            - 443:443 
            - 80:80 
                
    blog: 
        image: ghost:0.11
        volumes: 
            - /data/server/data/blog:/var/lib/ghost
        links:
            - db
          
        depends_on: 
            - db 
        
    fantasie: 
        image: ghost:latest
        volumes: 
            - /data/server/data/moritzblog:/var/lib/ghost/content
        environment:
            url: http://www.fantasie-geschichten.de
            database__client: mysql
            database__connection__host: db-fantasie
            database__connection__user: root
            database__connection__password: $mysql_pass
            database__connection__database: fantasie
        depends_on: 
            - db-fantasie

    db: 
        image: mysql
        volumes: 
            - /data/server/data/mysql:/var/lib/mysql
  
        environment: 
            - MYSQL_ROOT_PASSWORD=$mysql_pass

    db-fantasie: 
        image: mysql
        volumes: 
            - /data/server/data/fantasie_mysql:/var/lib/mysql
        environment: 
            - MYSQL_ROOT_PASSWORD=$mysql_pass
            - MYSQL_DATABASE=fantasie
